openapi: 3.0.3
info:
  title: OpenAPI schema for template terraform-alicloud-kafka
components:
  schemas:
    variables:
      type: object
      required:
      - infrastructure
      properties:
        infrastructure:
          title: Infrastructure
          type: object
          description: |
            Specify the infrastructure information for deploying.
          required:
          - vpc_id
          properties:
            kms_key_id:
              description: |
                Specify the KMS key ID which to encrypt the Kafka data. If not specified, the Kafka data will not be encrypted.
              nullable: true
              title: Kms Key Id
              type: string
              x-walrus-ui:
                order: 2
            vpc_id:
              description: |
                Specify the ID of the VPC where the Kafka service applies.
              title: Vpc Id
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 2
        storage:
          title: Storage
          type: object
          description: |
            Specify the disk type of the instance. 0: efficient cloud disk , 1: SSD.
          nullable: true
          properties:
            class:
              default: 0
              description: |
                Specify the disk type of the instance. 0: efficient cloud disk , 1: SSD.
              enum:
              - 0
              - 1
              nullable: true
              title: Class
              type: number
              x-walrus-ui:
                order: 1
            size:
              default: 500
              description: |
                Specify the size of the disk in megabyte.
              nullable: true
              title: Size
              type: number
              x-walrus-ui:
                order: 2
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 3
        seeding:
          title: Seeding
          type: array
          description: |
            Specify the configuration to kafka provisioning.
          items:
            properties:
              partitions:
                default: 1
                description: |
                  Specify the number of partitions for the topic.
                nullable: true
                title: Partitions
                type: number
                x-walrus-ui:
                  order: 2
              remark:
                default: Created by Walrus catalog, and provisioned by Terraform.
                description: |
                  Specify the remark for the topic.
                nullable: true
                title: Remark
                type: string
                x-walrus-ui:
                  order: 3
              topic:
                description: |
                  Specify the topic to be created when provisioning.
                nullable: true
                title: Topic
                type: string
                x-walrus-ui:
                  order: 1
            type: object
            x-walrus-ui:
              colSpan: 12
          nullable: true
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 4
      x-walrus-ui:
        groupOrder:
        - Basic
